{% set name = "pocl" %}
{% set version = "1.0rc1" %}
{% set build_number = "0" %}
{% set sha256 = "4cba46bbb024fa58bb1faabb3c63c89c139936f106271a90b2fad17e424655b3" %}
{% set llvm_version = "5.0.0" %}

# FIXME revert the URL below back to release

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # url: http://portablecl.org/downloads/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/pocl/pocl/archive/v1.0-RC1.tar.gz
  sha256: {{ sha256 }}

  patches:
  # Put binary paths built in pocl into a separate compilation unit
  # so that conda can successfully change them. (If they're not in
  # a separate compilation unit, the compiler has a habit of evaluating
  # strlen() and such at compile time.)
  - paths-in-separate-compilation-unit.patch

  # Disable unneeded macro workaround
  - fix-macros.patch

build:
  number: {{ build_number }}
  skip: True  # [not (unix or py>=35)]

requirements:
  build:
    - cmake
    - ocl-icd  # [linux]
    - libhwloc
    - libtool
    - pkg-config
    - llvmdev =={{ llvm_version }}
    - clangdev =={{ llvm_version }}
    - libcxx =={{ llvm_version }}
  run:
    - ocl-icd  # [linux]
    - clangdev =={{ llvm_version }}
    - libhwloc
    - libtool

test:
  commands:
    - test -f $PREFIX/lib64/libpocl.so  # [linux]
    - test -f $PREFIX/lib/libOpenCL.dylib  # [osx]

about:
  home: http://portablecl.org/
  license: MIT
  license_file: LICENSE
  summary: 'Portable Computing Language -- a CPU OpenCL implementation'
  dev_url: https://github.com/pocl/pocl

extra:
  recipe-maintainers:
    - inducer
    - mattwala
