travis:
  secure:
    BINSTAR_TOKEN: pDF9dVRvWSmStuetAPCi7sDFu1AvwEkCYwAyNi314dQS+9fmTtOlIlZAqI3OYS9PvkIrmEgMMmUs5hqrxhFMryuP6OANVai7FumzVXzU5+IFSGt12Q7r2VGIR26PS/5XScfgDeYCFgzOzN6RlrM92hCABn5ACc1+YATB+O/4UP6xW3/71yaTBjgRn8s6IOOTILMhiVLRmTEwhsOi4yajC63YdCA7fCCu4KguKFNMyHkSIjFdmtM/N1ftsVjfdTnAOjBxb5tRoAJhR7WQcZ42XplXaWhpdZybdI7I02TtfeLgik6NU5h7dPw0PVt9ckJtiFIRcxDmj+fld/YjJU0B+nzYADjW/UH4E58nPemMs+Fj/DxCg0fKbLb1nN6P08x2nCscifOygkVr8tEf2Wo4qQK/OIKzIF/SXw8c6hvbBsNMUzxOiL/k3JA3FboPWCtQK7pgoeiJzaeCiBU//pBayX2dDQX7CdxiSvmIHfdDeyRgfG1hWd4cMXMQDJGxBjbQkHKdqnvr5ZhVAq+JosZMiAdiciQgMevvG+jujFeNEoFcjltIurdjtgpw2ExmiRq68RTYSjsnoohGs0Xl4jAJo+FYA/SBqj4rs4LadzkSIFnWoouThriYt8Sk+97nKuptFpxYWeTP7E5Nh0IXPFRebTN/KYqP83ZqaEp068Z59Ig=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
