travis:
  secure:
    BINSTAR_TOKEN: I+Igqpmb8ahwdiffzWWgwlhXTgJbLnFHPemyIrpW8KPJqXxD5758i9/5fhv+HjxQI9G4JYcj2UMdWbvtcRIr9pMpZqnXb3nrakBtGEHupLq+oLwUO8iG9NEcuHyGBOxWpWIo2xgi1/QhOSzlbtJflunyQFIMP14f05bsnwUnzTtHDBaxzDgW6qLubkZx5bBCx8onyDOx+E4mEv/Lz9CTL6Pqti34Cab0KXN4dKaZvk8w1EODOgNezMQA4S81HhaEby6IeMJfPNDMC7cHAgau5qWIlrUOi9B6fng3jfsfgo6OUlzcH3L3KE8sq/d7N9yuCOfWh+Z1m53gJwCBdMsAIhfrKaS3wWcChj1GWr1oqVmBpn/Skdkdpx2u0rnVXSzVW4xIvFkE9BQzpqME8jd7lndH915sLoLhxjMaOgAglpgZyqp/jEXZ2AUgDBl3KnL9Rwk8w32nfArPgkVON/yNXXduYD+jX31uW13NQQhVp5N062lDBaixZ78ymVHTMCZ/4vLmV3OAN427EEyZCnUO17Db3nQy4NsRihAUlYLI8bD6FO/53+HBE5n6mGX+NiRHPNyjuTuX4+G4O8uqmwOJ6URAM+4ktbBd3HbbN7owoaYkPDPy4uMz4nExxuKrMv0NqmChoMggSkVmWwO4h/W4v1SXaviKGhNToO7iZfM0+Ns=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
